notifications:
  email:
    on_success: never
    on_failure: always

services:
  - docker

env:
  - DEMYX_USERNAME=demyx DEMYX_REPOSITORY=demyx DEMYX_VERSION=1.0.0

before_install:
  - docker pull demyx/docker-compose
  - docker pull demyx/docker-socket-proxy
  - docker pull demyx/mariadb
  - docker pull demyx/nginx
  - docker pull demyx/traefik
  - docker pull demyx/utilities
  - docker pull demyx/wordpress
  - docker pull demyx/wordpress:cli
  - docker pull alpine

script:
  - docker build --no-cache -t demyx/"$DEMYX_REPOSITORY" .
  - sudo cp host.sh /usr/local/bin/demyx
  - sudo chmod +x /usr/local/bin/demyx
  - sudo echo -e "DEMYX_HOST_DOMAIN=demyx.app\nDEMYX_HOST_EMAIL=info@demyx.app\nDEMYX_HOST_AUTH_USERNAME=travis\nDEMYX_HOST_IP=127.0.0.1\nDEMYX_HOST_INSTALL=false" > "$HOME"/.demyx
  - sudo demyx help
  - sudo demyx run demyx.app
  - sudo demyx wp demyx.app core is-installed
  - sudo demyx exec demyx.app nx wget -qO- http://localhost | grep 'Hello world'
  - sudo demyx motd

after_success:
  - echo "$DEMYX_PASSWORD" | docker login -u "$DEMYX_USERNAME" --password-stdin
  - docker push demyx/"$DEMYX_REPOSITORY":latest
  - docker push demyx/"$DEMYX_REPOSITORY":"$DEMYX_VERSION"
  - bash travis.sh
