notifications:
  email:
    on_success: never
    on_failure: always

services:
  - docker

env:
  - DEMYX_USERNAME=demyx DEMYX_REPOSITORY=demyx

before_install:
  - docker pull alpine
  - docker pull demyx/nginx-php-wordpress
  - docker pull demyx/mariadb
  - docker pull demyx/utilities
  - docker pull demyx/docker-compose
  - docker pull wordpress:cli

script:
  - docker build --no-cache -t demyx/"$DEMYX_REPOSITORY" docker/.
  - docker run -dt --rm --name demyx -v /var/run/docker.sock:/var/run/docker.sock:ro -v demyx:/demyx demyx/"$DEMYX_REPOSITORY"
  - sleep 5
  - docker exec -t demyx demyx motd
  - docker exec -t demyx demyx run domain.tld --auth --cdn --cache
  - docker exec -t demyx demyx wp domain.tld core is-installed

after_success:
  - echo "$DEMYX_PASSWORD" | docker login -u "$DEMYX_USERNAME" --password-stdin
  - docker push demyx/"$DEMYX_REPOSITORY"
  - bash travis.sh
