notifications:
  email:
    on_success: never
    on_failure: always

services:
  - docker

env:
  - DEMYX_USERNAME=demyx DEMYX_REPOSITORY=demyx

before_install:
  - docker pull demyx/docker-compose
  - docker pull demyx/docker-socket-proxy
  - docker pull demyx/mariadb:edge
  - docker pull demyx/nginx
  - docker pull demyx/ouroboros
  - docker pull demyx/traefik
  - docker pull demyx/utilities
  - docker pull demyx/wordpress
  - docker pull demyx/wordpress:cli
  - docker pull alpine

script:
  - export DEMYX_BUILD_DATE="$(date +%Y.%m.%d.%H%M%S)"
  - docker build --no-cache --build-arg DEMYX_BUILD="$DEMYX_BUILD_DATE" -t demyx/"$DEMYX_REPOSITORY" .
  - sudo cp chroot.sh /usr/local/bin/demyx
  - sudo chmod +x /usr/local/bin/demyx
  - sudo demyx --nc
  - sleep 5
  - sudo demyx cmd install --domain=domain.tld --email=info@domain.tld --user="$DEMYX_REPOSITORY" --pass="$DEMYX_REPOSITORY"
  - sudo demyx cmd stack ouroboros --false
  - sudo demyx cmd motd
  - sudo demyx cmd run domain.tld
  - sudo demyx cmd wp domain.tld core is-installed

after_success:
  - echo "$DEMYX_PASSWORD" | docker login -u "$DEMYX_USERNAME" --password-stdin
  - docker push demyx/"$DEMYX_REPOSITORY"
  - bash travis.sh
